name: dotnet-build

on:
  workflow_call:
    inputs:
      dotnet-version:
        type: string
        required: false
        default: 10.0.x
      target:
        type: string
        required: false
        default: .
      working-directory:
        type: string
        required: false
        default: .
      configuration:
        type: string
        required: false
        default: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore
        working-directory: ${{ inputs.working-directory }}
        run: dotnet restore "${{ inputs.target }}"

      - name: Build
        working-directory: ${{ inputs.working-directory }}
        run: dotnet build "${{ inputs.target }}" --configuration "${{ inputs.configuration }}" --no-restore
